name: Release

on:
  workflow_call:
    inputs:
      emscripten-version:
        description: The Emscripten version
        default: ${{vars.EMSCRIPTEN_VERSION || '3.1.64'}}
        type: string
      ubuntu-version:
        description: The version of the Ubuntu runner image
        default: ${{vars.UBUNTU_VERSION || '20.04'}}
        type: string

jobs:
  release:
    name: Build release artifacts
    runs-on: ubuntu-${{inputs.ubuntu-version}}
    env:
      REPO_NAME: ${{github.event.repository.name}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{inputs.emscripten-version}}
      - name: Set up tree-sitter CLI
        uses: tree-sitter/setup-action/cli@v1
      - name: Install parser dependencies
        run: |-
          JQ_SCRIPT='.dependencies | del(."node-addon-api", ."node-gyp-build") | length > 0'
          if jq -e "$JQ_SCRIPT" package.json >/dev/null; then
            npm i --omit dev --omit peer --omit optional
          fi
      - name: Generate parser
        run: tree-sitter generate
      #- name: Build Wasm binaries
      #  shell: bash
      #  run: |-
      #    while read -r grammar; do
      #      tree-sitter build --wasm "${grammar%/grammar.js}"
      #    done < <(find -name grammar.js -not -path './node_modules/*')
      - name: Push to Release Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
